
[Dimension]
	#Register Wasteland Dimension
	wasteland = true

[Biome]
	#Generate Wasteland Biome in Overworld
	wasteland = false

[Villages]
	#Generate Scientist House in Villages
	scientist_house = true
	#Add Wandering Trader trades
	wandering_trader_trades = true

